// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCat8_S86cRh6EKOdw1MkLdoOHyT6u_4tc',
    appId: '1:236908191532:web:118e6912024f1192a85689',
    messagingSenderId: '236908191532',
    projectId: 'anumealai-app',
    authDomain: 'anumealai-app.firebaseapp.com',
    storageBucket: 'anumealai-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCat8_S86cRh6EKOdw1MkLdoOHyT6u_4tc',
    appId: '1:236908191532:android:8f7f6912024f1192a85689',
    messagingSenderId: '236908191532',
    projectId: 'anumealai-app',
    storageBucket: 'anumealai-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjfng1eO_iapOTs5WD27wHIj1nN6KPebQ',
    appId: '1:236908191532:ios:298146ddcfe0a0eda85689',
    messagingSenderId: '236908191532',
    projectId: 'anumealai-app',
    storageBucket: 'anumealai-app.firebasestorage.app',
    iosBundleId: 'com.anumealai.anuMealAi',
  );
}
