import 'package:flutter/material.dart';
import 'legal_document_page.dart';

/// Complete In-App Terms of Use Document (§41, §75, §79).
class TermsOfUsePage extends StatelessWidget {
  const TermsOfUsePage({super.key});

  @override
  Widget build(BuildContext context) {
    return const LegalDocumentPage(
      title: 'Terms of Use',
      version: '1.0',
      effectiveDate: 'August 27, 2026',
      sections: [
        LegalSection(
          heading: '1. Acceptance of Terms',
          content:
              'By downloading, installing, or using AnuMealAI, you agree to be bound by these Terms of Use and our Privacy Policy. If you do not agree to these terms, please do not use the application.',
        ),
        LegalSection(
          heading: '2. Description of Service',
          content:
              'AnuMealAI provides artificial intelligence-powered culinary planning, mood-based recipe recommendations, pantry inventory tracking, and shopping list generation services.',
        ),
        LegalSection(
          heading: '3. User Accounts & Responsibilities',
          content:
              'You are responsible for maintaining the confidentiality of your login credentials and for all activities that occur under your account. You agree to provide accurate and complete information upon registration.',
        ),
        LegalSection(
          heading: '4. AI-Generated Content & Recipe Information',
          content:
              'Recipes, instructions, and cooking suggestions provided by AnuMealAI are generated by artificial intelligence. While we strive for accuracy, AI recommendations may occasionally contain unexpected combinations, timing estimates, or nutritional approximations.',
        ),
        LegalSection(
          heading: '5. Food Safety & Medical Disclaimer',
          content:
              'AnuMealAI does not provide medical or clinical nutritional advice. Recipe content is provided for informational and lifestyle purposes only. Always exercise caution and common sense regarding food freshness, internal cooking temperatures, cross-contamination, and specific dietary needs.',
        ),
        LegalSection(
          heading: '6. Allergies & Dietary Restrictions',
          content:
              'While AnuMealAI allows you to filter recipes by dietary preferences and known allergies, you remain solely responsible for verifying all ingredient labels, packaging, and preparation conditions before preparing or consuming food.',
        ),
        LegalSection(
          heading: '7. Subscriptions, Free Trials & Billing',
          content:
              'AnuMealAI offers optional auto-renewing subscriptions ("AnuMealAI Premium") providing unlimited recipe recommendations, advanced meal planning, and complete history access. Subscriptions are billed through your Apple App Store or Google Play Store account upon purchase confirmation.',
        ),
        LegalSection(
          heading: '8. Cancellation & Renewal',
          content:
              'Subscriptions renew automatically unless cancelled in your App Store or Google Play account settings at least 24 hours prior to the conclusion of the current billing cycle.',
        ),
        LegalSection(
          heading: '9. Intellectual Property',
          content:
              'All application design, code, branding, graphics, and interface elements are the proprietary intellectual property of the operator of AnuMealAI. All rights reserved.',
        ),
        LegalSection(
          heading: '10. Limitation of Liability',
          content:
              'To the maximum extent permitted by applicable law, AnuMealAI and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the application.',
        ),
        LegalSection(
          heading: '11. Contact Information',
          content:
              'For questions, feedback, or legal inquiries regarding these Terms of Use, please contact support@anumealai.app.',
        ),
      ],
    );
  }
}
