import 'package:flutter/material.dart';
import '../../../../core/constants/app_config.dart';
import 'legal_document_page.dart';

/// Complete In-App Terms of Use Document (§41, §75, §79).
/// Strictly aligned with Google Play Developer Policy, Apple App Store Guidelines,
/// and AI safety standards.
class TermsOfUsePage extends StatelessWidget {
  const TermsOfUsePage({super.key});

  @override
  Widget build(BuildContext context) {
    return const LegalDocumentPage(
      title: 'Terms of Use',
      version: '1.1',
      effectiveDate: 'August 27, 2026',
      externalUrl: AppConfig.termsOfUseUrl,
      sections: [
        LegalSection(
          heading: '1. Agreement to Terms',
          content:
              'By downloading, installing, accessing, or using the AnuMealAI mobile application ("App"), you agree to be bound by these Terms of Use ("Terms") and our Privacy Policy. If you do not agree to these Terms, you must not use or access the App.',
        ),
        LegalSection(
          heading: '2. Description of Services',
          content:
              'AnuMealAI provides artificial intelligence-powered culinary planning, mood-tailored recipe recommendations, pantry inventory management, meal scheduling, and smart shopping list generation.',
        ),
        LegalSection(
          heading: '3. User Accounts & Registration',
          content:
              'You may create an account using your email address or use the application as a guest. You are solely responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use.',
        ),
        LegalSection(
          heading: '4. AI Recipe Generation & Disclaimer',
          content:
              'Recipes, instructions, nutritional approximations, and cooking tips provided by AnuMealAI are generated by generative artificial intelligence models. While we continuously refine our algorithms for accuracy, recipes may occasionally contain unexpected ingredient combinations, varying cooking durations, or imprecise measurement estimates.\n\n'
              'You must exercise standard culinary judgment, check ingredient freshness, and follow safe food handling procedures when preparing any suggested meal.',
        ),
        LegalSection(
          heading: '5. Medical & Food Safety Disclaimer',
          content:
              'AnuMealAI is designed solely for informational, lifestyle, and recreational cooking purposes. The App DOES NOT provide certified medical, clinical, or dietary advice.\n\n'
              '• Allergens: Always verify allergen statements and ingredient packaging. AnuMealAI cannot guarantee that ingredients are free from trace allergens or cross-contamination.\n'
              '• Safe Cooking Temperatures: Ensure all meats, poultry, seafood, and eggs reach safe internal temperatures recommended by food safety authorities (e.g., USDA/FDA).',
        ),
        LegalSection(
          heading: '6. Subscriptions & In-App Purchases (AnuMealAI Pro)',
          content:
              'AnuMealAI offers optional premium auto-renewing subscriptions ("AnuMealAI Pro") that unlock unlimited recipe generation, extended weekly planner history, and priority AI features.\n\n'
              '• Billing: Payment will be charged to your Google Play or Apple App Store account upon confirmation of purchase.\n'
              '• Auto-Renewal: Subscriptions automatically renew unless auto-renew is turned off at least 24 hours before the end of the current billing period.\n'
              '• Management & Cancellation: You can manage or cancel your subscription at any time via your Google Play Account Settings or Apple Subscriptions Settings.',
        ),
        LegalSection(
          heading: '7. Intellectual Property & License',
          content:
              'The AnuMealAI application, code, visual design, graphics, trademarks, logos, and UI elements are the exclusive intellectual property of the operator of AnuMealAI. You are granted a personal, non-transferable, non-exclusive license to use the App for personal, non-commercial culinary planning.',
        ),
        LegalSection(
          heading: '8. Termination & Account Deletion',
          content:
              'You may terminate your agreement with AnuMealAI at any time by deleting your account through the in-app settings (Settings → Account & Security → Delete Account) or by uninstalling the App. We reserve the right to suspend or terminate accounts that violate these Terms or engage in abusive behavior.',
        ),
        LegalSection(
          heading: '9. Limitation of Liability',
          content:
              'To the fullest extent permitted by applicable law, AnuMealAI, its creators, and affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits, data, or personal injury resulting from your use of or inability to use the App or any prepared recipes.',
        ),
        LegalSection(
          heading: '10. Governing Law',
          content:
              'These Terms shall be governed by and construed in accordance with the applicable laws, without regard to its conflict of law provisions.',
        ),
        LegalSection(
          heading: '11. Support & Contact Information',
          content:
              'If you have any questions or feedback regarding these Terms of Use, please contact our support team at support@anumealai.app.',
        ),
      ],
    );
  }
}
